### ISSUE TITLE
Is the SYNOPSIS wrong?

### ISSUE THREAD

**Issue by worthmine** [houseabsolute/DateTime-Format-ISO8601#12]
Hi, I've met something strange.

At the [SYNOPSIS](https://metacpan.org/pod/DateTime::Format::ISO8601#SYNOPSIS),

```perl
use DateTime::Format::ISO8601;
 
my $str = '2020-07-25T11:32:31';
 
my $dt = DateTime::Format::ISO8601->parse_datetime($str);
$dt = DateTime::Format::ISO8601->parse_time($str);
...
```

when I run it within my test script, It says `Invalid date format: 2020-07-25T11:32:31 ~` and dies at the end of lines.
It is strange.

And, I succeeded to pass this situation like this:

```perl
my $str = '2020-07-25T11:32:31';
say 'parse_datetime: ', my $dt = DateTime::Format::ISO8601->parse_datetime($str);
# parse_datetime: 2020-07-25T11:32:31    # correct

( undef, my $time ) = split 'T', $dt;
$time =~ s/://g;
say 'parse_time: ', $dt = DateTime::Format::ISO8601->parse_time($time);
# parse_time: 2020-10-12T11:32:31            # is it correct?
```

In [DateTime](https://metacpan.org/pod/DateTime), there is no definition for `parse_time`.
And there is [no document](https://metacpan.org/pod/DateTime::Format::ISO8601#parse_time) for `parse_time`.

What does `parse_time` mean?

**Comment by autarch** [comment]
That's definitely a bug in the synopsis. The `parse_time` method will only accept times, like `12:13:14`, not a full datetime.

**Comment by worthmine** [comment]
thank you for fast replying!

it still strange because:

```
my $dt = DateTime::Format::ISO8601->parse_datetime($str);
( undef, my $time ) = split 'T', $dt;
#$time =~ s/://g;     # it seems this line is required to pass
say 'parse_time: ', $dt = DateTime::Format::ISO8601->parse_time($time);
# said "Invalid date format: 11:32:31 at ~"
```

**Comment by autarch** [comment]
That looks like a _separate_ bug. The `parse_time` method _should_ be able to parse that format, but for some reason it's not.

**Comment by worthmine** [comment]
I'm not in a hurry, but when will it be fixed?

**Comment by autarch** [comment]
I'd certainly welcome a PR to fix these issues. Otherwise it'll be whenever I get around to it. Typically I do FOSS stuff on weekends, so maybe this weekend.

**Comment by worthmine** [comment]
I'd like to try to fix it indeed. but  I'm busy until this Thursday 15. 
Probably, I'll wait for your fix your own.

best regard.

**Comment by autarch** [comment]
So I did some more digging and I realized `parse_time` is working as intended. That method is only used for formats which might be either a date or a time. The `parse_time` method treats those as a time, whereas `parse_datetime` will treat them as a date.

**Comment by autarch** [comment]
Fixed in 0.15.

**Comment by worthmine** [comment]
Thank you for fast fixing.
Lastly, I have a question about README.

At [5.3 Time of Day](https://github.com/houseabsolute/DateTime-Format-ISO8601#53-time-of-day),
there is a mention to the format 'hh:mm:ss' as chapter 5.3.1.1,
but it still fails to parse this format with  `parse_time()`.

```example.pl
use feature qw(say);
use DateTime::Format::ISO8601;

my $time_str = '23:32:31';
$dt = DateTime::Format::ISO8601->parse_time($time_str); # dies here
say $dt;
```

Is this a spec?
